// <auto-generated />
namespace SharePointPnP.ProvisioningApp.DomainModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Wave9OAuthConsumerApps20190730 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Wave9OAuthConsumerApps20190730));
        
        string IMigrationMetadata.Id
        {
            get { return "201907300935043_Wave9-OAuthConsumerApps-20190730"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
