// <auto-generated />
namespace SharePointPnP.ProvisioningApp.DomainModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Wave7PackageVisibility20190715 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Wave7PackageVisibility20190715));
        
        string IMigrationMetadata.Id
        {
            get { return "201907151025570_Wave7-PackageVisibility-20190715"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
