// <auto-generated />
namespace SharePointPnP.ProvisioningApp.DomainModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Wave3NotificationRecipients : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Wave3NotificationRecipients));
        
        string IMigrationMetadata.Id
        {
            get { return "201901081157406_Wave3-NotificationRecipients"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
