// <auto-generated />
namespace SharePointPnP.ProvisioningApp.DomainModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Wave5DesignReview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Wave5DesignReview));
        
        string IMigrationMetadata.Id
        {
            get { return "201903041454365_Wave5-DesignReview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
