// <auto-generated />
namespace SharePointPnP.ProvisioningApp.DomainModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Wave8PackageProperties20190725 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Wave8PackageProperties20190725));
        
        string IMigrationMetadata.Id
        {
            get { return "201907251439290_Wave8-PackageProperties-20190725"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
