// <auto-generated />
namespace SharePointPnP.ProvisioningApp.DomainModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Wave11LookBookSiteStep3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Wave11LookBookSiteStep3));
        
        string IMigrationMetadata.Id
        {
            get { return "201910071521270_Wave11-LookBookSite-Step3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
