// <auto-generated />
namespace SharePointPnP.ProvisioningApp.DomainModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Wave12ProvisioningPackagesId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Wave12ProvisioningPackagesId));
        
        string IMigrationMetadata.Id
        {
            get { return "202006241213349_Wave12-Provisioning-PackagesId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
