// <auto-generated />
namespace SharePointPnP.ProvisioningApp.DomainModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Wave12ForceExistingSite : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Wave12ForceExistingSite));
        
        string IMigrationMetadata.Id
        {
            get { return "202007010515497_Wave12-ForceExistingSite"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
